---
title: "Diferencias_espacialesEO_contaminacion"
author: "Grupo 6"
date: "2024-04-06"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(dplyr)
library(tidyr)
library(fmsb)
library(pheatmap)
library(ComplexHeatmap)
library(missMDA)
library(FactoMineR)
library(factoextra)
library(gridExtra)
library(patchwork)

```

## Diferencias espaciales de contaminación: ESTE vrs. OESTE

# PCA

```{r Fig1, message=FALSE, warning=FALSE}

# 1 Leer csv

# 1.1 Carga de datos
air_quality_gijon <- 
  read.csv("C:/Users/asus/Desktop/RGit/Datathon-2024/data/datathon24_parte1/air_quality_gijon.csv")
comparativa_total <- air_quality_gijon[, 1:13]    # Solo las comparativas
comparativa <- comparativa_total[, -5]          # Sin NO
comparativa <- comparativa[, -5]                # Sin NO2 duplicado

# 1.2 Tabla en versión PCA
nueva_tabla <- pivot_longer(comparativa, 
                             cols = starts_with(c("SO2", "NO2", "CO", "PM10", "O3")), 
                             names_to = c(".value", "Zona"),
                             names_sep = "_")

# 1.3 Tabla con Este y Oeste
nueva_tabla <- nueva_tabla %>%
               mutate(Zona = ifelse(Zona == "EsteAvdaCastilla", "Este", 
                                   ifelse(Zona == "OesteAvdaArgentina", "Oeste", Zona)))

# 1.4 Tabla sin datos entre 2020-03-01 >=> 2021-05-09
nueva_tabla$date <- as.Date(nueva_tabla$date)
nueva_tabla <- nueva_tabla %>%
               filter(!(date >= as.Date("2020-03-01") & date <= as.Date("2021-05-09")))

# 1.5 Tabla con columna Año_Mes
nueva_tabla <- nueva_tabla %>%
               mutate(Year_Month = substr(date, 1, 7))

# 1.6 Con medias por Año_Mes
tabla_resumen <- nueva_tabla %>%
  group_by(Year_Month, Zona) %>%
  summarize(
    SO2 = mean(SO2, na.rm = TRUE),
    NO2 = mean(NO2, na.rm = TRUE),
    CO = mean(CO, na.rm = TRUE),
    PM10 = mean(PM10, na.rm = TRUE),
    O3 = mean(O3, na.rm = TRUE)
  )

# 1.7 Columna con meses
tabla_resumen <- tabla_resumen %>%
  mutate(Month = substr(Year_Month, 6, 7))

# 1.8 Columna con estaciones del año y ordenar columnas
tabla_resumen <- tabla_resumen %>%
  mutate(Season = case_when(
    Month %in% c("04", "05", "06") ~ "Primavera",
    Month %in% c("07", "08", "09") ~ "Verano",
    Month %in% c("10", "11", "12") ~ "Otoño",
    TRUE ~ "Invierno" # Para los meses de enero a marzo
  ))

columnas <- names(tabla_resumen)
nuevo_orden <- c(columnas[1], columnas[8:9], columnas[-c(1, 9:10)])
tabla_resumen <- tabla_resumen[nuevo_orden]
tabla_resumen <- tabla_resumen[, -10]   


# 2. Estandarización




# 3. PCA 

# 3.1 Confidence level
confi <- 0.70

# 3.2 PCA function
perform_pca_analysis <-function(data, title) {
  
  # Impute missing data
  imputed_data <- imputePCA(data[c(5:ncol(data))], method = "Regularized")
  pca_result <- PCA(imputed_data, graph = TRUE)
 
   # Biplots
  Time <- data$Season
  Situation <- data$Zona
  
  # Especifica las paletas de colores
  colores <- c("#4682B4", "#800080")  # Azul y morado
  
  biplot <- fviz_pca_biplot(pca_result, geom = "point", col.ind = Situation, 
                            shape.ind = Time,
                            invisible = "var",
                            addEllipses = TRUE, ellipse.level = confi,
                            col.ind.palette = colores, shape.ind.palette = colores) +
    theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold")) +
    ggtitle(title)
  
  return(biplot)
}


general_biplot <- perform_pca_analysis(tabla_resumen, "General analysis")



```


# Heatmap

```{r Fig1, message=FALSE, warning=FALSE}

# 1 Leer csv

# 1.1 Carga de datos
air_quality_gijon <- 
  read.csv("C:/Users/asus/Desktop/RGit/Datathon-2024/data/datathon24_parte1/air_quality_gijon.csv")
comparativa_total <- air_quality_gijon[, 1:13]    # Solo las comparativas
comparativa <- comparativa_total[, -5]          # Sin NO
comparativa <- comparativa[, -5]                # Sin NO2 duplicado

# 1.2 Tabla en versión PCA
nueva_tabla <- pivot_longer(comparativa, 
                             cols = starts_with(c("SO2", "NO2", "CO", "PM10", "O3")), 
                             names_to = c(".value", "Zona"),
                             names_sep = "_")

# 1.3 Tabla con Este y Oeste
nueva_tabla <- nueva_tabla %>%
               mutate(Zona = ifelse(Zona == "EsteAvdaCastilla", "Este", 
                                   ifelse(Zona == "OesteAvdaArgentina", "Oeste", Zona)))

# 1.4 Tabla sin datos entre 2020-03-01 >=> 2021-05-09
nueva_tabla$date <- as.Date(nueva_tabla$date)
nueva_tabla <- nueva_tabla %>%
               filter(!(date >= as.Date("2020-03-01") & date <= as.Date("2021-05-09")))

# 1.5 Tabla con columna Año_Mes
nueva_tabla <- nueva_tabla %>%
               mutate(Year_Month = substr(date, 1, 7))

# 1.6 Con medias por Año_Mes
tabla_resumen <- nueva_tabla %>%
  group_by(Year_Month, Zona) %>%
  summarize(
    SO2 = mean(SO2, na.rm = TRUE),
    NO2 = mean(NO2, na.rm = TRUE),
    CO = mean(CO, na.rm = TRUE),
    PM10 = mean(PM10, na.rm = TRUE),
    O3 = mean(O3, na.rm = TRUE)
  )

# 1.7 Columna con meses
tabla_resumen <- tabla_resumen %>%
  mutate(Month = substr(Year_Month, 6, 7))

# 1.8 Columna con estaciones del año y ordenar columnas
tabla_resumen <- tabla_resumen %>%
  mutate(Season = case_when(
    Month %in% c("04", "05", "06") ~ "Primavera",
    Month %in% c("07", "08", "09") ~ "Verano",
    Month %in% c("10", "11", "12") ~ "Otoño",
    TRUE ~ "Invierno" # Para los meses de enero a marzo
  ))

columnas <- names(tabla_resumen)
nuevo_orden <- c(columnas[1], columnas[8:9], columnas[-c(1, 9:10)])
tabla_resumen <- tabla_resumen[nuevo_orden]
tabla_resumen <- tabla_resumen[, -10]   

# 1.9 Separar por variables
SO2_tabla <- tabla_resumen[, 1:5]
NO2_tabla <- tabla_resumen[, c(1:4, 6)]
CO_tabla <- tabla_resumen[, c(1:4, 7)]
PM10_tabla <- tabla_resumen[, c(1:4, 8)]
O3_tabla <- tabla_resumen[, c(1:4, 9)]


# 2. Data representation

SO2_heatmap <- ggplot(SO2_tabla, aes(x = Zona, y = Season, fill = SO2)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "#98FB98", high = "#FFA07A") +
  labs(title = "SO2",
       x = "Zona",
       y = "") +
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, size = 20), 
    axis.text = element_text(size = 16), 
    axis.title = element_text(size = 16)  
  )

NO2_heatmap <- ggplot(NO2_tabla, aes(x = Zona, y = Season, fill = NO2)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "#98FB98", high = "#FFA07A") +
  labs(title = "NO2",
       x = "Zona",
       y = "") +
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, size = 20), 
    axis.text = element_text(size = 16), 
    axis.title = element_text(size = 16)  
  )

CO_heatmap <- ggplot(CO_tabla, aes(x = Zona, y = Season, fill = CO)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "#98FB98", high = "#FFA07A") +
  labs(title = "CO",
       x = "Zona",
       y = "") +
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, size = 20), 
    axis.text = element_text(size = 16), 
    axis.title = element_text(size = 16)  
  )

PM10_heatmap <- ggplot(PM10_tabla, aes(x = Zona, y = Season, fill = PM10)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "#98FB98", high = "#FFA07A") +
  labs(title = "PM10",
       x = "Zona",
       y = "") +
  theme_minimal()+
  theme(
    plot.title = element_text(hjust = 0.5, size = 20), 
    axis.text = element_text(size = 16), 
    axis.title = element_text(size = 16)  
  )

O3_heatmap <- ggplot(O3_tabla, aes(x = Zona, y = Season, fill = O3)) +
  geom_tile(color = "white") + 
  scale_fill_gradient(low = "#98FB98", high = "#FFA07A") +
  labs(title = "O3",
       x = "Zona",
       y = "") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 20), 
    axis.text = element_text(size = 16), 
    axis.title = element_text(size = 16)  
  )


plot_heatmaps <- SO2_heatmap + NO2_heatmap + 
  CO_heatmap + PM10_heatmap + O3_heatmap + 
  plot_layout(ncol = 5) 


```


